# Generated by Django 5.1.4 on 2026-08-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('accident', 'Accident'), ('breakdown', 'Breakdown'), ('delay', 'Delay'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
